version: '3.1'

services:
  service_doc:
    container_name: service_doc
    build: .
    volumes:
      - ./docs:/etc/Sphinx/source
      - ./build:/etc/Sphinx/build
    environment:
      - IS_LOCAL_BUILD=1
    ports:
      - 8100:80

    
    

